import json

# Check the source JSON
with open('semantic_similarity/mbpp_all_with_embedding_and_relevance_v2.json') as f:
    data = json.load(f)

print(f'📊 SOURCE DATA TRACE')
print('='*60)
print(f'File: semantic_similarity/mbpp_all_with_embedding_and_relevance_v2.json')
print(f'Total documents: {len(data)}')
print()
print(f'Entry Structure:')
entry = data[0]
print(f'  Keys: {list(entry.keys())}')
print(f'  prompt: {entry["prompt"][:60]}...')
print(f'  relevant_indices: {entry.get("relevant_indices", "N/A")}')
print(f'  has embedding: {"embedding" in entry}')
print()
print('='*60)
print('PIPELINE: qrels_manual.csv')
print('='*60)
print('1️⃣  Load dataset → mbpp_all_with_embedding_and_relevance_v2.json')
print(f'   └─ {len(data)} documents')
print()
print('2️⃣  Compute embeddings untuk setiap prompt')
print('   └─ Normalized embeddings')
print()
print('3️⃣  Sample 200 random queries (seed=42)')
print('   └─ generate_qrels.py: --manual-queries 200')
print()
print('4️⃣  Untuk setiap query, ranking top 20 candidates by similarity')
print('   └─ generate_qrels.py: --manual-candidates 20')
print()
print('5️⃣  Generate template: qrels_manual_template.csv')
print('   └─ 200 queries × 20 candidates = 4000 rows')
print('   └─ Columns: query_id, query_text, doc_id, doc_text, pred_score, rank_hint, rel (empty), notes')
print()
print('6️⃣  Manual labeling → Fill kolom "rel" (0-3)')
print('   └─ query_id=3,13,17,20,21,29,32,33 dalam qrels_manual.csv')
print('   └─ 0=not relevant, 3=highly relevant')
print()
print('7️⃣  FINAL: qrels_manual.csv')
print('   └─ 200 queries × 20 candidates = 4000 rows dengan labels')
